<script lang="ts" setup>

const initState = () => ({
    icon: 'bell'
})

const icons = [
    '360',
    'accessibility',
    'activeCabinVentilation',
    'add',
    'adjust',
    'arrowDoubleDown',
    'arrowDoubleLeft',
    'arrowDoubleRight',
    'arrowDoubleUp',
    'arrowDown',
    'arrowFirst',
    'arrowHeadDown',
    'arrowHeadLeft',
    'arrowHeadRight',
    'arrowHeadUp',
    'arrowLast',
    'arrowLeft',
    'arrowRight',
    'arrowUp',
    'augmentedReality',
    'batteryEmpty',
    'batteryFull',
    'bell',
    'bookmark',
    'broadcast',
    'calculator',
    'calendar',
    'camera',
    'car',
    'carBattery',
    'card',
    'chargingActive',
    'chargingState',
    'chargingStation',
    'chart',
    'chat',
    'check',
    'city',
    'climate',
    'climateControl',
    'clock',
    'close',
    'closedCaption',
    'co2Emission',
    'compare',
    'configurate',
    'countryRoad',
    'cubicCapacity',
    'delete',
    'disable',
    'document',
    'download',
    'duration',
    'edit',
    'email',
    'exclamation',
    'external',
    'filter',
    'flash',
    'fuelStation',
    'garage',
    'gift',
    'globe',
    'grid',
    'highway',
    'home',
    'horn',
    'image',
    'increase',
    'information',
    'key',
    'leaf',
    'leather',
    'light',
    'list',
    'locate',
    'lock',
    'lockOpen',
    'logoBaidu',
    'logoDelicious',
    'logoDigg',
    'logoFacebook',
    'logoFoursquare',
    'logoGmail',
    'logoGoogle',
    'logoHatena',
    'logoInstagram',
    'logoKaixin',
    'logoKakaotalk',
    'logoLinkedin',
    'logoNaver',
    'logoPinterest',
    'logoQq',
    'logoQqShare',
    'logoReddit',
    'logoSkyrock',
    'logoSohu',
    'logoTecent',
    'logoTelegram',
    'logoTiktok',
    'logoTumblr',
    'logoTwitter',
    'logoViber',
    'logoVk',
    'logoWechat',
    'logoWeibo',
    'logoWhatsapp',
    'logoXing',
    'logoYahoo',
    'logoYouku',
    'logoYoutube',
    'logout',
    'map',
    'menuDotsHorizontal',
    'menuDotsVertical',
    'menuLines',
    'minus',
    'mobile',
    'moon',
    'oilCan',
    'parkingBrake',
    'parkingLight',
    'pause',
    'phone',
    'pin',
    'play',
    'plug',
    'plus',
    'preheating',
    'printer',
    'purchase',
    'question',
    'racingFlag',
    'refresh',
    'replay',
    'reset',
    'route',
    'rss',
    'save',
    'screen',
    'search',
    'send',
    'share',
    'shoppingBag',
    'shoppingCart',
    'sidelights',
    'snowflake',
    'sort',
    'stack',
    'star',
    'steeringWheel',
    'stopwatch',
    'subtract',
    'success',
    'sun',
    'switch',
    'tablet',
    'tachometer',
    'truck',
    'upload',
    'user',
    'userGroup',
    'userManual',
    'video',
    'view',
    'viewOff',
    'volumeOff',
    'volumeUp',
    'warning',
    'weight',
    'wifi',
    'work',
    'wrench',
    'wrenches',
    'zoomIn',
    'zoomOut',
]
</script>

<template>
    <Story title="v2/pds/Icon" icon="material-symbols:add" :layout="{
        type: 'grid',
    }">
        <Variant title="Playground" :init-state="initState">
            <template #default="{ state }">
                <p-icon :name="state.icon"></p-icon>
            </template>
            <template #controls="{ state }">
                <!-- Interact with state here -->
                <HstSelect title="Variant" :options="icons" v-model="state.icon"></HstSelect>
            </template>
        </Variant>
        <Variant :title="icon" v-for="icon of icons">
            <p-icon :name="icon"></p-icon>
        </Variant>
    </Story>
</template>
<docs lang="md">
# PDS Button

Official documentation [here](https://designsystem.porsche.com/v2/components/icon/examples)
</docs>